"""Modbus/TCP Zeek Detection Rule Generator.

Generates Zeek (formerly Bro) detection scripts for Modbus/TCP anomalies.
Implements the purple team use case taught in Daryus IoT/ICS course (2026):
capture Modbus PCAP -> detect unauthorized writes -> generate SIEM alerts.

Generated rules detect:
  - Write_Coil/Write_Holding_Register from unauthorized hosts
  - Modbus device enumeration (Report_Slave_ID, Read_Device_ID)
  - Modbus DoS patterns (rapid sequential requests)
  - Function code abuse (dangerous FCs on unusual hosts)

Reference: Daryus IoT course - Dia 3 DPI/Detection lab
Reference: MITRE ATT&CK ICS T0836 (Modify Parameter), T0855 (Unauthorized Command)

Author: Andre Henrique (@mrhenrike) | Uniao Geek
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from industrialxpl.core.exploit import *


@dataclass
class ModbusZeekConfig:
    """Configuration for Modbus Zeek rule generation.

    Attributes:
        allowed_masters: IP addresses authorized to write to PLCs.
        plc_hosts: IP addresses of monitored PLCs/RTUs.
        alert_write_from_unauthorized: Detect writes from non-master hosts.
        alert_enum_fc: Detect enumeration function codes (43, 17).
        alert_rapid_requests: Detect request rate anomalies (DoS indicator).
        rapid_threshold: Requests per second to trigger rapid-request alert.
        output_path: File path for generated Zeek script.
        log_prefix: Prefix for Zeek Notice type names.
    """

    allowed_masters: List[str] = field(default_factory=lambda: ["192.168.1.5"])
    plc_hosts: List[str] = field(default_factory=lambda: ["192.168.1.10"])
    alert_write_from_unauthorized: bool = True
    alert_enum_fc: bool = True
    alert_rapid_requests: bool = True
    rapid_threshold: int = 20
    output_path: str = ".tmp/modbus_detection.zeek"
    log_prefix: str = "Modbus"


def _generate_zeek_script(config: ModbusZeekConfig) -> str:
    """Generate a Zeek Modbus detection script.

    Args:
        config: ModbusZeekConfig with detection parameters.

    Returns:
        Complete Zeek script as string.
    """
    allowed_set = ", ".join(f'"{ip}"' for ip in config.allowed_masters)
    plc_set = ", ".join(f'"{ip}"' for ip in config.plc_hosts)
    threshold = config.rapid_threshold

    parts = [
        "# ================================================================",
        "# Modbus/TCP Anomaly Detection - Generated by IndustrialXPL-Forge",
        f"# Author: Andre Henrique (@mrhenrike) | Uniao Geek",
        "# Reference: MITRE ATT&CK ICS T0836, T0855",
        "# Daryus IoT/ICS Course - Purple Team Detection Lab",
        "# ================================================================",
        "",
        "@load base/protocols/modbus",
        "@load base/frameworks/notice",
        "",
        "module ModbusSecurity;",
        "",
        "export {",
        "    redef enum Notice::Type += {",
        f"        {config.log_prefix}::UnauthorizedWrite,",
        f"        {config.log_prefix}::EnumerationAttempt,",
        f"        {config.log_prefix}::RapidRequests,",
        f"        {config.log_prefix}::DangerousFC,",
        "    };",
        "",
        f"    const allowed_masters: set[addr] = {{ {allowed_set} }} &redef;",
        f"    const monitored_plcs: set[addr] = {{ {plc_set} }} &redef;",
        f"    const rapid_req_threshold: count = {threshold} &redef;",
        "}",
        "",
        "# Track request rates per source",
        "global req_count: table[addr] of count &default=0;",
        "global req_window: table[addr] of time &default=network_time();",
        "",
    ]

    if config.alert_write_from_unauthorized:
        parts += [
            "# Detect unauthorized Modbus write commands",
            "event modbus_write_coils(c: connection, headers: ModbusHeaders,",
            "                        start_address: count, coils: ModbusCoil) {",
            "    local src = c$id$orig_h;",
            "    local dst = c$id$resp_h;",
            "    if (dst in monitored_plcs && src !in allowed_masters) {",
            "        NOTICE([",
            f"            $note={config.log_prefix}::UnauthorizedWrite,",
            '            $msg=fmt("Unauthorized Modbus Write_Coil from %s to %s addr=%d", src, dst, start_address),',
            "            $conn=c,",
            "            $identifier=cat(src, dst),",
            "        ]);",
            "    }",
            "}",
            "",
            "event modbus_write_registers(c: connection, headers: ModbusHeaders,",
            "                             start_address: count, registers: ModbusRegisters) {",
            "    local src = c$id$orig_h;",
            "    local dst = c$id$resp_h;",
            "    if (dst in monitored_plcs && src !in allowed_masters) {",
            "        NOTICE([",
            f"            $note={config.log_prefix}::UnauthorizedWrite,",
            '            $msg=fmt("Unauthorized Modbus Write_Registers from %s to %s addr=%d count=%d", src, dst, start_address, |registers|),',
            "            $conn=c,",
            "            $identifier=cat(src, dst),",
            "        ]);",
            "    }",
            "}",
            "",
        ]

    if config.alert_enum_fc:
        parts += [
            "# Detect Modbus enumeration (Report Slave ID FC=17, Read Device ID FC=43)",
            "event modbus_read_device_identification(c: connection, headers: ModbusHeaders,",
            "                                         level: count, object_id: count) {",
            "    NOTICE([",
            f"        $note={config.log_prefix}::EnumerationAttempt,",
            '        $msg=fmt("Modbus device identification probe from %s to %s (FC43)", c$id$orig_h, c$id$resp_h),',
            "        $conn=c,",
            "    ]);",
            "}",
            "",
        ]

    if config.alert_rapid_requests:
        parts += [
            "# Detect rapid Modbus request bursts (potential DoS)",
            "event modbus_message(c: connection, headers: ModbusHeaders, is_orig: bool) {",
            "    local src = c$id$orig_h;",
            "    local now = network_time();",
            "    if (src !in req_window || now - req_window[src] > 1sec) {",
            "        req_count[src] = 0;",
            "        req_window[src] = now;",
            "    }",
            "    req_count[src] += 1;",
            f"    if (req_count[src] > {threshold}) {{",
            "        NOTICE([",
            f"            $note={config.log_prefix}::RapidRequests,",
            '            $msg=fmt("Modbus rapid request burst from %s: %d req/s", src, req_count[src]),',
            "            $conn=c,",
            "            $suppress_for=30sec,",
            "        ]);",
            "    }",
            "}",
            "",
        ]

    parts += [
        "# End of generated Modbus detection script",
    ]

    return "\n".join(parts)


class Exploit(Exploit):
    """Modbus Zeek Detection Rule Generator.

    Generates a production-ready Zeek (Bro) Modbus detection script
    for defending OT/ICS networks. Implements the purple team detection
    use case from the Daryus IoT/ICS course (2026 edition, Dia 3).

    Author: Andre Henrique (@mrhenrike) | Uniao Geek
    """

    __info__ = {
        "name": "Modbus Zeek Detection Rule Generator",
        "category": "detection",
        "type": "purple_team",
        "description": (
            "Generates a Zeek detection script for Modbus/TCP anomalies including "
            "unauthorized write commands, device enumeration, rapid request bursts. "
            "Implements the purple team 'DPI/detection' use case from Daryus IoT course. "
            "Output is a .zeek file ready to load into a Zeek sensor."
        ),
        "authors": ("Andre Henrique (@mrhenrike) | Uniao Geek",),
        "references": (
            "https://docs.zeek.org/en/master/scripts/base/protocols/modbus/",
            "https://attack.mitre.org/techniques/T0836/",
            "Daryus IoT/ICS Course - Dia 3 Lab (DPI and detection)",
        ),
        "usage": (
            "ixf > use assessment/detection/modbus_zeek_rule_generator\n"
            "ixf (ModbusZeek) > set allowed_masters 192.168.1.5\n"
            "ixf (ModbusZeek) > set plc_hosts 192.168.1.10,192.168.1.20\n"
            "ixf (ModbusZeek) > set output_path /etc/zeek/local/modbus_detection.zeek\n"
            "ixf (ModbusZeek) > run"
        ),
    }

    allowed_masters = OptString(
        "192.168.1.5",
        "Comma-separated IPs authorized to send Modbus write commands"
    )
    plc_hosts = OptString(
        "192.168.1.10",
        "Comma-separated IPs of monitored PLCs/RTUs"
    )
    rapid_threshold = OptInteger(20, "Requests per second to trigger rapid-burst alert")
    output_path = OptString(".tmp/modbus_detection.zeek", "Output file path for Zeek script")
    alert_writes = OptBool(True, "Alert on unauthorized write commands")
    alert_enum = OptBool(True, "Alert on enumeration function codes (FC43, FC17)")
    alert_rapid = OptBool(True, "Alert on rapid request bursts")

    @mute
    def check(self) -> bool:
        """Check if output directory is writable.

        Returns:
            True if can create output file.
        """
        try:
            out = Path(str(self.output_path))
            out.parent.mkdir(parents=True, exist_ok=True)
            return True
        except Exception:
            return False

    def run(self) -> None:
        """Generate Zeek Modbus detection script."""
        masters = [m.strip() for m in str(self.allowed_masters).split(",") if m.strip()]
        plcs = [p.strip() for p in str(self.plc_hosts).split(",") if p.strip()]

        config = ModbusZeekConfig(
            allowed_masters=masters,
            plc_hosts=plcs,
            alert_write_from_unauthorized=bool(self.alert_writes),
            alert_enum_fc=bool(self.alert_enum),
            alert_rapid_requests=bool(self.alert_rapid),
            rapid_threshold=int(self.rapid_threshold),
            output_path=str(self.output_path),
        )

        script = _generate_zeek_script(config)
        out = Path(config.output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(script, encoding="utf-8")

        print_success(f"Zeek script generated: {out}")
        print_info(f"Authorized masters: {masters}")
        print_info(f"Monitored PLCs: {plcs}")
        print_info(f"Script size: {len(script)} characters, {script.count(chr(10))} lines")
        print_table(
            ("Detection Rule", "Enabled"),
            ("Unauthorized write (FC5/FC6/FC15/FC16)", str(bool(self.alert_writes))),
            ("Device enumeration (FC43/FC17)", str(bool(self.alert_enum))),
            (f"Rapid requests (>{self.rapid_threshold}/s)", str(bool(self.alert_rapid))),
        )
        print_info(
            f"Load in Zeek: zeek -C -r capture.pcap {out} "
            "or add to /etc/zeek/local.zeek"
        )
