"""ICS/OT Lab Environment Setup Assistant.

Generates Docker Compose configurations and setup scripts for
spinning up ICS/OT lab environments used in the Daryus IoT course.

Lab components (as referenced in Daryus Relatório 03 and student research):
  - Conpot: ICS honeypot (Modbus, S7comm, HTTP HMI, DNP3)
  - FUXA: Modern SCADA platform with web HMI
  - OpenPLC: Open-source PLC runtime (Modbus slave)
  - ModbusPal: Java-based Modbus simulator
  - Labshock: Docker ICS lab (removed from submodules, recreated here)

Reference commands (Daryus course README):
  java -jar ModbusPal.jar
  pip install pyModbusTCP
  docker run -p 502:502 -p 80:80 mushorg/conpot

Author: Andre Henrique (@mrhenrike) | Uniao Geek
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from industrialxpl.core.exploit import *


_DOCKER_COMPOSE_TEMPLATE = """version: '3.8'

# ICS/OT Lab Environment
# Generated by IndustrialXPL-Forge
# Daryus IoT/ICS Security Course
# Author: Andre Henrique (@mrhenrike) | Uniao Geek
#
# Usage:
#   docker compose up -d
#   docker compose ps          # Check status
#   docker compose logs -f     # Follow logs
#   docker compose down        # Stop all

networks:
  ics_lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
{services}

# ================================================================
# Lab access:
#   Conpot Modbus:   172.20.0.10:502
#   Conpot HTTP HMI: http://172.20.0.10:80
#   Conpot S7comm:   172.20.0.10:102
#   FUXA SCADA:      http://172.20.0.20:1881
#   OpenPLC:         http://172.20.0.30:8080 (admin:openplc)
#                    Modbus: 172.20.0.30:502
# ================================================================
"""

_CONPOT_SERVICE = """  conpot:
    image: mushorg/conpot:latest
    container_name: ics_lab_conpot
    ports:
      - "502:502"
      - "80:80"
      - "102:102"
      - "20000:20000/udp"
      - "161:161/udp"
    networks:
      ics_lab:
        ipv4_address: 172.20.0.10
    restart: unless-stopped
    command: ["--template", "default"]
"""

_FUXA_SERVICE = """  fuxa:
    image: frangoteam/fuxa:latest
    container_name: ics_lab_fuxa
    ports:
      - "1881:1881"
    volumes:
      - fuxa_data:/usr/src/app/_appdata
    networks:
      ics_lab:
        ipv4_address: 172.20.0.20
    restart: unless-stopped
"""

_OPENPLC_SERVICE = """  openplc:
    image: openplcproject/openplc:v3
    container_name: ics_lab_openplc
    ports:
      - "8080:8080"
      - "44818:44818"
    environment:
      - OPENPLC_PORT=502
    networks:
      ics_lab:
        ipv4_address: 172.20.0.30
    restart: unless-stopped
"""

_ATTACKER_SERVICE = """  attacker:
    image: kalilinux/kali-rolling:latest
    container_name: ics_lab_attacker
    stdin_open: true
    tty: true
    networks:
      ics_lab:
        ipv4_address: 172.20.0.100
    command: ["bash", "-c", "apt-get update -q && apt-get install -q -y nmap python3 python3-pip && pip3 install pymodbus pyModbusTCP && bash"]
"""

_SETUP_SCRIPT = """#!/bin/bash
# ICS/OT Lab Setup Script - Daryus IoT/ICS Course
# Author: Andre Henrique (@mrhenrike) | Uniao Geek

set -e

echo "[*] ICS/OT Lab Environment Setup"
echo "[*] Components: Conpot + FUXA + OpenPLC"
echo ""

# Check Docker
if ! command -v docker &>/dev/null; then
    echo "[!] Docker not found. Install from: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! command -v docker-compose &>/dev/null && ! docker compose version &>/dev/null; then
    echo "[!] Docker Compose not found."
    exit 1
fi

# Pull images
echo "[*] Pulling Docker images..."
docker pull mushorg/conpot:latest
docker pull frangoteam/fuxa:latest

# Start lab
echo "[*] Starting lab environment..."
docker compose up -d

echo "[*] Waiting for services to start..."
sleep 5

echo ""
echo "[+] Lab environment ready!"
echo ""
echo "    Conpot Modbus TCP:  172.20.0.10:502"
echo "    Conpot HTTP HMI:    http://localhost:80"
echo "    Conpot S7comm:      172.20.0.10:102"
echo "    FUXA SCADA:         http://localhost:1881"
echo "    OpenPLC:            http://localhost:8080 (admin:openplc)"
echo ""
echo "[*] Test Modbus with:"
echo "    nmap --script modbus-discover -p 502 172.20.0.10"
echo "    python3 -c \\"from pymodbus.client import ModbusTcpClient; c=ModbusTcpClient('172.20.0.10',port=502); c.connect(); print(c.read_holding_registers(0,10))\\""
echo ""
echo "[*] Stop lab with: docker compose down"
"""


@dataclass
class LabConfig:
    """ICS lab environment configuration.

    Attributes:
        include_conpot: Include Conpot honeypot.
        include_fuxa: Include FUXA SCADA.
        include_openplc: Include OpenPLC runtime.
        include_attacker: Include Kali attacker container.
        output_dir: Directory to write docker-compose.yml and setup.sh.
    """

    include_conpot: bool = True
    include_fuxa: bool = True
    include_openplc: bool = False
    include_attacker: bool = False
    output_dir: str = ".tmp/ics_lab"


class Exploit(Exploit):
    """ICS/OT Lab Environment Setup Assistant.

    Generates Docker Compose configurations and setup scripts for
    spinning up ICS/OT lab environments. Based on lab setups from
    the Daryus IoT/ICS security course (Labshock, Conpot, FUXA).

    Author: Andre Henrique (@mrhenrike) | Uniao Geek
    """

    __info__ = {
        "name": "ICS/OT Lab Environment Setup Assistant",
        "category": "lab",
        "type": "educational",
        "description": (
            "Generates Docker Compose files and setup scripts for ICS/OT lab environments. "
            "Components: Conpot (Modbus/S7comm honeypot), FUXA (SCADA HMI), OpenPLC. "
            "Based on Daryus IoT course labs and Labshock architecture. "
            "Provides a ready-to-run Docker environment for practicing Modbus attacks "
            "and defenses in isolation."
        ),
        "authors": ("Andre Henrique (@mrhenrike) | Uniao Geek",),
        "references": (
            "https://github.com/mushorg/conpot",
            "https://frangoteam.org/ (FUXA SCADA)",
            "https://openplcproject.com/",
            "Daryus IoT Course - Relatório 03 research: Labshock/Conpot lab",
        ),
        "lab_components": {
            "Conpot 172.20.0.10": "Modbus:502, HTTP:80, S7comm:102, DNP3:20000",
            "FUXA  172.20.0.20": "SCADA HMI web: 1881",
            "OpenPLC 172.20.0.30": "Web:8080, EtherNetIP:44818, Modbus slave",
        },
    }

    include_conpot = OptBool(True, "Include Conpot ICS honeypot")
    include_fuxa = OptBool(True, "Include FUXA SCADA platform")
    include_openplc = OptBool(False, "Include OpenPLC runtime")
    include_attacker = OptBool(False, "Include Kali attacker container")
    output_dir = OptString(".tmp/ics_lab", "Output directory for generated files")

    @mute
    def check(self) -> bool:
        """Check output directory is writable.

        Returns:
            True if directory can be created.
        """
        try:
            Path(str(self.output_dir)).mkdir(parents=True, exist_ok=True)
            return True
        except Exception:
            return False

    def run(self) -> None:
        """Generate ICS lab Docker Compose and setup scripts."""
        out = Path(str(self.output_dir))
        out.mkdir(parents=True, exist_ok=True)

        # Build service list
        services_str = ""
        volumes_str = ""
        components = []

        if bool(self.include_conpot):
            services_str += _CONPOT_SERVICE
            components.append("Conpot (172.20.0.10) - Modbus/S7comm/HTTP")

        if bool(self.include_fuxa):
            services_str += _FUXA_SERVICE
            volumes_str = "\nvolumes:\n  fuxa_data:\n"
            components.append("FUXA SCADA (172.20.0.20) - Web HMI :1881")

        if bool(self.include_openplc):
            services_str += _OPENPLC_SERVICE
            components.append("OpenPLC (172.20.0.30) - PLC runtime :8080")

        if bool(self.include_attacker):
            services_str += _ATTACKER_SERVICE
            components.append("Kali Attacker (172.20.0.100)")

        if not services_str:
            print_error("No components selected. Enable at least one service.")
            return

        compose_content = _DOCKER_COMPOSE_TEMPLATE.format(services=services_str) + volumes_str

        # Write docker-compose.yml
        compose_file = out / "docker-compose.yml"
        compose_file.write_text(compose_content, encoding="utf-8")

        # Write setup.sh
        setup_file = out / "setup.sh"
        setup_file.write_text(_SETUP_SCRIPT, encoding="utf-8")

        # Write lab notes
        notes_file = out / "LAB_NOTES.md"
        notes_content = f"""# ICS/OT Lab - Daryus IoT Security Course

## Components
{chr(10).join('- ' + c for c in components)}

## Quick Start
```bash
cd {out}
bash setup.sh
```

## Attack Exercises (Dia 3)

### 1. Modbus Discovery
```bash
nmap --script modbus-discover.nse --script-args='modbus-discover.aggressive=true' -p 502 172.20.0.10
```

### 2. Read Holding Registers (FC3)
```python
from pymodbus.client import ModbusTcpClient
c = ModbusTcpClient('172.20.0.10', port=502)
c.connect()
result = c.read_holding_registers(0, 10)
print(result.registers)
```

### 3. Write Coil (FC5) - DANGEROUS
```python
c.write_coil(1, True)   # FC5 - toggle output
```

### 4. Capture + Analyze with Wireshark
```bash
tshark -i eth0 -f "tcp port 502" -w /tmp/modbus_capture.pcap
# Then analyze with IndustrialXPL-Forge:
# ixf > use assessment/detection/modbus_pcap_analyzer
```

### 5. Access FUXA HMI
Open http://localhost:1881 to configure SCADA simulation

## Defense Exercises (Dia 4)
Generate Suricata/Zeek rules:
```
ixf > use assessment/detection/suricata_ot_rules_generator
ixf > use assessment/detection/modbus_zeek_rule_generator
```

## Reference
- Daryus IoT/ICS Course - Dia 3: Modbus lab
- NIST SP 800-82r3
- IEC 62443-3-2 Zone/Conduit model
"""
        notes_file.write_text(notes_content, encoding="utf-8")

        print_success(f"Lab environment files generated in: {out}")
        print_table(
            ("File", "Purpose"),
            ("docker-compose.yml", "Docker services definition"),
            ("setup.sh", "Automated setup script"),
            ("LAB_NOTES.md", "Lab exercises guide"),
        )
        print_info(f"Start lab: cd {out} && bash setup.sh")
        print_info(f"Stop lab: cd {out} && docker compose down")
        print_table(
            ("Component", "Access"),
            *[(c.split(" - ")[0], c.split(" - ")[1] if " - " in c else "") for c in components]
        )
